version: '3'

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - configuration=${CONFIGURATION}
    container_name: danielzotti_${CONFIGURATION}
    image: dz/danielzotti_${CONFIGURATION}
    expose:
      - 4000
#    ports:
#      - "${PORT}:4000"
    restart: unless-stopped
