FROM node:14.12.0-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install -g @angular/cli

COPY . .

EXPOSE 4201

CMD ng serve --host 0.0.0.0 --port 4201
# NB: --disableHostCheck option doesn't work!