##################
# BUILD container
##################
FROM node:10.16.3-alpine as buildContainer

# set working directory
WORKDIR /app

# install dependencies
COPY ./package.json ./package-lock.json /app/
RUN npm install
COPY . /app

# build app
RUN npm run build:ssr

##################
# APP container
##################
FROM node:10.16.3-alpine

WORKDIR /app

# Copy dependency definitions
COPY --from=buildContainer /app/package.json /app

# Get all the code needed to run the app
COPY --from=buildContainer /app/dist /app/dist

# Expose the port the app runs in
EXPOSE 4000

# Serve the app
CMD npm run serve:ssr