version: '3'

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: danielzotti_local
    image: dz/danielzotti_local
    ports:
      - "4201:4201"
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules