version: '3.7'

services:

  dev:
    container_name: danielzotti_dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'
    expose:
      - 80
    environment:
      - "VIRTUAL_HOST=${VIRTUAL_HOST:-www.danielzotti.dev.local}"

networks:
  default:
    external:
      name: nginx-proxy
