version: '3'

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - configuration=${CONFIGURATION}
    container_name: danielzotti_${CONFIGURATION}
    image: dz/danielzotti
    ports:
      - "${PORT}:4000"
    restart: unless-stopped
