version: '3'

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - configuration=${CONFIGURATION}
    container_name: me_danielzotti_it
    image: dz/me_danielzotti_it
    ports:
      - "${PORT}:4000"
    restart: unless-stopped
